screen -d -m -S cansetup bash -c 'source /home/dash/.bashrc; setupcan; exec bash'
screen -d -m -S roscore bash -c 'source /home/dash/dash/os/catkin_ws/devel/setup.bash ; roscore; exec bash'
screen -d -m -S gpio bash -c 'source /home/dash/dash/os/catkin_ws/devel/setup.bash; rosrun gpio gpio_node; exec bash'
screen -d -m -S can bash -c 'source /home/dash/dash/os/catkin_ws/devel/setup.bash; rosrun can_to_qt_bolt3 can_talker_bolt3; exec bash'
screen -d -m -S qt bash -c './BoltDash; exec bash'
