######################################################################
# Automatically generated by qmake (3.0) Sat Mar 18 08:30:09 2017
######################################################################

TEMPLATE = app
TARGET = interface
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h rosprocess.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp rosprocess.cpp
